services:
  db:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  api:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./app
          action: sync
          target: /app
          ignore:
            - ./.venv
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./app/htmlcov:/agrifunding-backend/app/htmlcov
      - ./app/:/agrifunding-backend/app/:cached
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  mailcatcher:
    image: schickling/mailcatcher
    container_name: ${COMPOSE_PROJECT_NAME}-mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
