"""add_additional_data_on_item

Revision ID: b4d3069dd898
Revises: 26aae429c316
Create Date: 2025-05-05 10:49:00.989423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b4d3069dd898'
down_revision = '26aae429c316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('item', sa.Column('submission_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('target_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('fund_actual', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('fund_target', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('item', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('item', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=True)
    op.add_column('user', sa.Column('job', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'job')
    op.alter_column('item', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('item', 'longitude')
    op.drop_column('item', 'latitude')
    op.drop_column('item', 'status')
    op.drop_column('item', 'fund_target')
    op.drop_column('item', 'fund_actual')
    op.drop_column('item', 'target_date')
    op.drop_column('item', 'submission_date')
    op.drop_column('item', 'summary')
    op.drop_column('item', 'rating')
    # ### end Alembic commands ###
